### ISSUE TITLE
Is there any reason why TrifingerPlatform class initiates a TrifingerPro by hardcode?

### ISSUE THREAD

**Issue by IrvingF7** [open-dynamic-robot-initiative/trifinger_simulation#109]
On this line, I noticed that the TrifingerPlatform constructs the instance by calling Pro via a hardcoded manner

https://github.com/open-dynamic-robot-initiative/trifinger_simulation/blob/5313fee3d2880b79e0aa6bbd6a637c72259cd987/trifinger_simulation/trifinger_platform.py#L195

Is there any specific reason for this?

I noticed that if I simply changed the string to `trifingeredu`, the demo scripts worked fine (at least judging from visualization)

But just to be on the safer side, I want to make sure changing this is okay. (So nothing in the codebase depends on this string being `trifingerpro`

I would also like to make this an initialization argument to the TriFingerPlatform class by sending a pull request if allowed.

Anyway, thank you for your time and opening source this awesome codebase

**Comment by luator** [comment]
Hello,
to be honest, the reason is just a bit of laziness and lack of need from our side (we don't have a "Platform" (i.e. robot + cameras) with the Edu version of the robot here).  But I think it should be no problem to change the type to "trifingeredu" and I'm happy to accept a PR to make this configurable.

One thing to consider, though: The camera placement would be a bit different with TriFingerEdu, so this would need to be taken into account somehow.

If the goal is to match an existing physical setup as good as possible, the best solution would probably be to allow camera initialisation with [`create_trifinger_camera_array_from_config`](https://github.com/open-dynamic-robot-initiative/trifinger_simulation/blob/5313fee3d2880b79e0aa6bbd6a637c72259cd987/trifinger_simulation/camera.py#L593C5-L593C46) instead of `TriFingerCameras` (it takes camera poses and intrinsic parameters from yaml files that can be obtained by calibrating the real cameras).  Maybe we could add an optional argument to pass the camera calibration files.  If set, it uses `create_trifinger_camera_array_from_config`, otherwise it falls back to the current behaviour.


> Anyway, thank you for your time and opening source this awesome codebase

Thanks :)

**Comment by IrvingF7** [comment]
I see. Thanks. I agree with your judgment that the camera will have to be different. I could make a really simple pull request where I only change the parameters of trifinger platform, but that feels kinda trivial. In the future if I ever need to model the camera according to the real EDU version I will make a pull request then! 

Thank you for your time!
